# action.yml
name: PerfAction for JMeter
description: Run performance tests using JMeter test plan
author: NaveenKumar Namachivayam - https://qainsights.com

branding:
  color: blue
  icon: feather

inputs:
  test-plan-path:
    required: true
    description: jmeter test plan to execute
  args:
    required: false
    description: Optional arguments. For more details https://jmeter.apache.org/usermanual/get-started.html#non_gui

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "-n"
  - "-t"
  - "${{ inputs.test-plan-path }}"
  - "-l"
  - "result.jtl"
  - "${{ inputs.args }}"
