# action.yml
name: PerfAction for JMeter
description: Run performance tests using JMeter test plan
author: NaveenKumar Namachivayam - https://qainsights.com

branding:
  color: blue
  icon: feather

inputs:
  test-plan-path:
    required: true
    description: JMeter test plan to execute
  results-file:
    required: false
    description: Where to store the results e.g., result.csv
    default: result.jtl    
  args:
    required: false
    description: Optional arguments. For more details https://jmeter.apache.org/usermanual/get-started.html#non_gui

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "-n"
  - "-t"
  - "${{ inputs.test-plan-path }}"
  - "-l"
  - "${{ inputs.results-file }}"
  - "${{ inputs.args }}"
